# Generated by Django 4.2.6 on 2023-12-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shooting_tver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='Логин')),
                ('email', models.CharField(max_length=50, verbose_name='E-mail')),
                ('password1', models.CharField(max_length=50, verbose_name='Пароль')),
                ('password2', models.CharField(max_length=50, verbose_name='Повторите пароль')),
            ],
            options={
                'verbose_name': 'Тренировку',
                'verbose_name_plural': 'Тренировки',
            },
        ),
    ]
