# Generated by Django 4.2.6 on 2023-12-03 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Тренировку', 'verbose_name_plural': 'Тренировки'},
        ),
        migrations.AlterField(
            model_name='articles',
            name='time',
            field=models.TimeField(verbose_name='Время тренировки'),
        ),
    ]
